version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-erp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - mini-erp-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: mini-erp-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - mini-erp-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mini-erp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mini_erp
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_PASSWORD: db_password
      MYSQL_USER: db_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mini-erp-mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mini-erp-network

networks:
  mini-erp-network:
    driver: bridge

volumes:
  mini-erp-mysql:
    driver: local